### ISSUE TITLE
[Bug]Bot goes offline after using setProfile

### ISSUE THREAD

**Issue by newaccforhc** [ZhongXiLu/NaoTomori#3]
After I used setProfile command, bot went offline and unresponsive... I checked Heroku Logs but they don't show anything about crashing.

Logs if you want (I restarted the app retried using setProfile and waited 3 hours to see if it crashes):
https://del.dog/ihingeloll

**Comment by ZhongXiLu** [comment]
Thanks for reporting the found bugs.

I fixed your other issues, but I'm not sure if I fixed this one too. Either way, I recommend redeploying to Heroku with the new fixes. I'll try to keep an eye out for it as well and see if it's still broken.

**Comment by newaccforhc** [comment]
@ZhongXiLu Thanks for update.. But, now the bot stays offline forever..

Updating and running logs: 
https://del.dog/othivilerr

Logs show that bot crashed several times overnight (I was asleep).. Bot was offline when I woke up.. I restarted it some time ago.. Bot didn't come online at all..

**Comment by ZhongXiLu** [comment]
Thanks for reporting again (the logs also helped).

The bug should be fixed now. There was a problem with long lists which caused the bot to timeout and shutdown.

It might still take a while for your profile to update, but at least your bot should stay online. Also, if you haven't recreated your app on Heroku yet, please do to recreate the database, which is needed (or re-add the `Heroku Postgres` plugin).

**Comment by newaccforhc** [comment]
Okay.. Thanks...I'll recreate the app..

**Comment by newaccforhc** [comment]
@ZhongXiLu Looks like the bot doesn't go offline now.. But, setProfile command doesn't work (I waited for more than 4 hours).. The logs show some errors..

Logs: https://del.dog/gudufiheti


I'll reopen this issue and change the title.

**Comment by ZhongXiLu** [comment]
@newaccforhc Did you delete the app from Heroku and added it again?

**Comment by newaccforhc** [comment]
I deleted the Postgres plug-in and added it again.

**Comment by ZhongXiLu** [comment]
@newaccforhc That doesn't seem to work. It's probably the best if you create a whole new app.

**Comment by newaccforhc** [comment]
Okay.. Thanks!
I'll recreate the app and report back here.

**Comment by newaccforhc** [comment]
@ZhongXiLu Sorry I took long time to reply.. But, looks like the issue is fixed after recreating the app..
Thanks!!

**Comment by ZhongXiLu** [comment]
@newaccforhc I just fixed that now; there was an issue if your MyAnimeList account did not have a profile picture. Sorry for all the trouble btw. 😢 

Also, Discord has changed its api recently, so you should enable `PRESENCE INTENT` (Privileged Gateway Intents section) on [https://discordapp.com/developers/applications/me](https://discordapp.com/developers/applications/me) if you haven't done that already.

**Comment by newaccforhc** [comment]
@ZhongXiLu Thanks for the bot and quick replies...
I'll enable it now.
