### ISSUE TITLE
[Feature] Option to get notified only for anime or manga

### ISSUE THREAD

**Issue by newaccforhc** [ZhongXiLu/NaoTomori#5]
Not a bug or any must-add feature, but it'll be nice to get an option to enable/disable notifications for anime or manga.. Currently, the bot notifies for both anime and manga, but I don't really want to get notified for mangas.
Well, it might be just me.. 

Thanks if you decide to add it tho.

**Comment by ZhongXiLu** [comment]
I added your feature. You can now remove the anime or manga source, so you wont receive any notifications anymore for any anime or manga.

`!setMangaSource none` to remove the manga source in your case

**Comment by newaccforhc** [comment]
Oh thanks!!
