### ISSUE TITLE
Heroku fails to Build App.

### ISSUE THREAD

**Issue by BreezeGH** [ZhongXiLu/NaoTomori#7]
When using the existing application template displayed on the github page, it opens into Heroku properly and has access to the github properly. When using a working application name, region, and using the correct discord token, it responds with:
`
-----> Building on the Heroku-20 stack
-----> Python app detected
 !     Requested runtime (python-3.7.3) is not available for this stack (heroku-20).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed`
under Build App.

**Comment by BreezeGH** [comment]
Pretty self-explanatory fix.

**Comment by ZhongXiLu** [comment]
I've changed the Python version, should be fixed now.
